### ISSUE TITLE
CSV File Import Issue

### ISSUE THREAD

**Issue by isaiahnields** [ericfabreu/WearFlashcards#1]
I am not able to select a CSV file that I have created to import. The file has the .csv extension. Am I missing something or is this a bug? Attached is a screenshot of the file select screen.

![screenshot nov 26 2016 14 03 50](https://cloud.githubusercontent.com/assets/12752162/20642605/44ec9de0-b3e1-11e6-8852-32909e188a3c.png)

**Comment by ericfabreu** [comment]
Sorry for the delay. The filename is "Untitled spreadsheet", so I'm assuming you probably created your file using Excel. Did you make sure to save the file as a .csv instead of renaming the .xlsx extension to .csv? Just renaming the extension won't work and the app won't be able to recognize the file since it still has the MIME type of a spreadsheet. If the file was saved correctly, you should be able to open it with a simple text editor such as TextEdit, Gedit, or Notepad.

If it opens correctly there, could you please email the file to me?

**Comment by isaiahnields** [comment]
I exported to CSV from a Google sheet. I had already checked the file with TextEdit, etc. It theoretically should be formatted correctly. Perhaps it's specifically an issue with Google sheet exporting. See attached for the file. I changed the extension to .txt because .csv was failing to upload.

[Untitled spreadsheet - Sheet1.txt](https://github.com/ericfabreu/WearFlashcards/files/617836/Untitled.spreadsheet.-.Sheet1.txt)

**Comment by ericfabreu** [comment]
Oh, I just realized what is going on. You're trying to select the file in the "Downloads" section and everything is grayed out there for some reason. This is a bug, but I don't know if it's caused by my app. My app always opens to the Downloads folder by default. I'll try to force it to open there by default with the next release. 

Meanwhile, you can try clicking on the hamburger menu, choosing either your device or a file manager, and opening your file from there.

**Comment by isaiahnields** [comment]
Your suggestion worked. Thanks for the help and the free app.

**Comment by ericfabreu** [comment]
You're welcome
